name: Publish package

on:
  push:
    paths:
      - .github/workflows/publish.yml

env:
  version: "0.0.4"

jobs:
  build-xfce4-hotcorner-plugin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt update && sudo apt-get install wget tree tar build-essential dpkg binutils intltool xfce4-dev-tools xorg-dev libglib2.0-dev libgtk-3-dev libwnck-3-dev libxfce4ui-2-dev libxfce4panel-2.0-dev libnotify-dev

    - name: Build
      run: |
        wget -O xfce4-hotcorner-plugin-${{ env.version }}.tar.gz https://github.com/christopherkobayashi/xfce4-hotcorner-plugin/archive/refs/tags/${{ env.version }}.tar.gz
        tar -xvf xfce4-hotcorner-plugin-${{ env.version }}.tar.gz
        cd xfce4-hotcorner-plugin-${{ env.version }}
        mkdir usr
        ./configure --prefix=/home/runner/work/xfce4-hotcorner-plugin/xfce4-hotcorner-plugin/xfce4-hotcorner-plugin-${{ env.version }}/usr
        make
        make install

    - name: Build Deb File
      run: |
        cd xfce4-hotcorner-plugin-${{ env.version }}
        mkdir xfce4-hotcorner-plugin
        cp -R /home/runner/work/xfce4-hotcorner-plugin/xfce4-hotcorner-plugin/DEBIAN /home/runner/work/xfce4-hotcorner-plugin/xfce4-hotcorner-plugin/xfce4-hotcorner-plugin-${{ env.version }}/xfce4-hotcorner-plugin/
        cp -R usr xfce4-hotcorner-plugin
        dpkg -b xfce4-hotcorner-plugin

    - name: Automatic Release
      uses: marvinpinto/action-automatic-releases@latest
      with: 
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.version }}
        prerelease: false
        title:  "Latest Build ${{ env.version }}"
        files: |
          xfce4-hotcorner-plugin-${{ env.version }}/*.deb
